# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Xu Han
tagline:          'A Jekyll theme'
description:      'Research Assistant at Johns Hopkins University'
url:              http://xuhanevans.io
baseurl:          /

author:
  name:           'Xu Han'
  mail:           'xhan32@jhu.edu'
  url:            'http://xuhanevans.io'


paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet